/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function variableBlur(input: VariableBlurInput): Buffer

export interface VariableBlurAdvancedOptions {
  mode?: string
  steps?: number
  maxLevels?: number
  targetLocalSigma?: number
  minLocalSigma?: number
  maxLocalSigma?: number
  downsampleStageSigma?: number
}

export interface VariableBlurInput {
  buffer: Buffer
  options: VariableBlurOptions
}

export interface VariableBlurOptions {
  x: number
  y: number
  start?: number
  end?: number
  quality?: number
  maxSigma: number
  curve?: string
  advanced?: VariableBlurAdvancedOptions
  outputFormat?: string
}

export declare function variableBlurRaw(input: VariableBlurRawInput): Buffer

export interface VariableBlurRawInput {
  data: Buffer
  width: number
  height: number
  channels: number
  options: VariableBlurOptions
}
